paths: ["vendor/certificationy/symfony-pack/data", "vendor/certificationy/php-pack/data", "vendor/dchabanenko/magento-pack/data"]
manifest_uri: "https://raw.githubusercontent.com/TheRatG/certificationy-cli/gh-pages/manifest.json"